# Generated by Django 4.1.7 on 2023-04-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='meal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
