# Generated by Django 4.1.7 on 2023-04-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_galleryimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
