# Generated by Django 4.1.7 on 2023-04-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_baseinfo_options_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinfo',
            name='welcome_image',
            field=models.ImageField(default=0, upload_to='Images/BaseInfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='Gallery/Images/%Y/%M/%d'),
        ),
    ]
