# Generated by Django 4.1.7 on 2023-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_baseinfo_welcome_image_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=0, upload_to='Images/Staff/%Y/%M'),
            preserve_default=False,
        ),
    ]
