# Generated by Django 4.1.7 on 2023-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_about_room_description_room_price_staff_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
