# Generated by Django 4.1.7 on 2023-04-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_rename_about_meal_description_meal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
