# Generated by Django 4.1.7 on 2023-04-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designate whether the document is active for use and download.'),
        ),
    ]
