# Generated by Django 4.1.7 on 2023-04-04 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 16, 50, 15, 310054, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
